// PLACEHOLDER — this file is normally fully generated by the FlutterFire
// CLI and should NOT be hand-maintained long-term.
//
// Run (after `flutter create .` has generated ios/android, per
// docs/SETUP.md):
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// That command overwrites this file with real per-platform Firebase config
// pulled from your Firebase project. Until then, `Firebase.initializeApp`
// in main.dart will fail at runtime — that's expected for a fresh scaffold.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io' show Platform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isIOS) return ios;
    throw UnsupportedError(
      'DefaultFirebaseOptions: only iOS is configured in this scaffold '
      '(iOS-first per design doc). Run `flutterfire configure` once '
      'Android support is added.',
    );
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'pingpic-dev',
    storageBucket: 'REPLACE_ME',
    iosBundleId: 'com.pingpic.app',
  );
}
