import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'app.dart';
import 'firebase_options.dart';
import 'features/notifications/data/push_notification_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // NOTE: this will throw until firebase_options.dart is regenerated by
  // `flutterfire configure` with real project config — see the comment in
  // that file and docs/SETUP.md.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Must be registered before runApp, and the handler itself must be a
  // top-level function (see its doc comment in push_notification_service.dart)
  // — this is what lets the home screen widget update even when a prompt
  // notification arrives while the app is fully terminated.
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

  runApp(const ProviderScope(child: PingPicApp()));
}
